{-# LANGUAGE BlockArguments    #-}
{-# LANGUAGE OverloadedStrings #-}

module Html where

import           Data.Text (Text)
import           Lucid
import           PaceRange
import           RaceDistance
import           RunTime as RT
import           VDOT
import Text.Printf

index :: Html ()
index = indexMaybeError Nothing


-- todo only display custom distance when custom is selected
-- radio buttons and show when checked?
-- NB: `style_` generated by ChatGPT.
indexMaybeError :: Maybe Text -> Html ()
indexMaybeError maybeError = do
  html_ do
    head_ do
      title_ "VDOT Calculator"
      style_ "body { font-family: Arial, sans-serif; background: #f2f6fb; color: #1f2937; margin: 0; padding: 32px 16px; } .card { max-width: 700px; margin: 0 auto 16px auto; background: #ffffff; border-radius: 12px; box-shadow: 0 8px 24px rgba(0,0,0,0.08); padding: 24px; } h1, h2 { margin-top: 0; } p { margin: 0 0 14px 0; } ul { margin: 0 0 14px 20px; padding: 0; } li { margin-bottom: 6px; } label { display: block; font-weight: 600; margin-bottom: 6px; } input, select, button { font-size: 1rem; } input, select { width: 100%; box-sizing: border-box; padding: 10px; border: 1px solid #cbd5e1; border-radius: 8px; } button { margin-top: 8px; background: #2563eb; color: white; border: 0; border-radius: 8px; padding: 10px 14px; cursor: pointer; } button:hover { background: #1d4ed8; } .error { background: #fef2f2; color: #991b1b; border: 1px solid #fecaca; border-radius: 8px; padding: 10px; } a { color: #2563eb; text-decoration: none; font-weight: 600; } a:hover { text-decoration: underline; }"
    body_ do
      div_ [class_ "card"] do
        h1_ "Norwegian Singles Calculator"
        p_ "Calculate optimal training paces using the Norwegian Singles method"
        maybe mempty (p_ [class_ "error"] . toHtml) maybeError
        form_ [action_ "/result", method_ "get"] do
          p_ do
            label_ "Time"
            input_ [type_ "text", name_ "time", placeholder_ "5:30"]
          p_ do
            label_ "Race distance"
            select_ [name_ "dist"] do
              mapM_ (\preset -> option_ [value_ (presetValue preset)] (toHtml (presetLabel preset))) presetRaceDistances
              option_ [value_ "custom"] "Custom distance"
          p_ do
            label_ "Custom distance (meters)"
            input_ [type_ "number", name_ "customDist", min_ "1", max_ "50000", placeholder_ "8500"]
          div_ "only used when Custom distance is selected from dropdown"
          button_ [type_ "submit"] "Analyze"
      div_ [class_ "card"] do
        h2_ "About Norwegian Singles"
        p_ "The Norwegian Singles method is a training approach that emphasizes sub-threshold training to maximize adaptations while minimizing fatigue."
        p_ "Key principles:"
        ul_ do
          li_ "2-3 quality sessions per week plus 1 long run"
          li_ "Quality work comprises 20-25% of weekly running time"
          li_ "Maintain sub-threshold state (2.5-3.5 mmol/L lactate)"
          li_ "Keep easy runs extremely easy (hardmax 70% of max heart rate)"
        p_ "This calculator helps you determine appropriate paces for interval sessions based on your current fitness level, measured through VDOT, Critical Speed, or Critical Power."
        p_ do
          "Learn more from the "
          a_ [href_ "https://www.reddit.com/r/NorwegianSinglesRun/wiki/index/", target_ "_blank"] "Reddit"
          " Wiki."

-- todo ?
-- RaceTime :: Text
-- or InputTime :: Text
-- NB: `style_` generated by ChatGPT.
resultPage :: VDOT -> [(Text, Text)] -> [PaceRange] -> Html ()
resultPage vdot raceTable intervalPaces = do
  html_ do
    head_ do
      title_ "VDOT Result"
      style_ "body { font-family: Arial, sans-serif; background: #f2f6fb; color: #1f2937; margin: 0; padding: 32px 16px; } .card { max-width: 700px; margin: 0 auto; background: #ffffff; border-radius: 12px; box-shadow: 0 8px 24px rgba(0,0,0,0.08); padding: 24px; } h1, h2 { margin-top: 0; } table { width: 100%; border-collapse: collapse; margin-bottom: 18px; } th, td { text-align: left; border-bottom: 1px solid #e2e8f0; padding: 8px; } th { background: #f8fafc; } a { color: #2563eb; text-decoration: none; font-weight: 600; } a:hover { text-decoration: underline; }"
    body_ do
      div_ [class_ "card"] do
        h1_ "result"
        p_ $ "VDOT: " >> toHtml (printf "%.1f" vdot :: String) -- display with 1 decimal
        h2_ "equiv race times"
        table_ do
          mapM_ (\(d, t) -> tr_ (td_ (toHtml d) >> td_ (toHtml t))) raceTable
        h2_ "interval pace ranges"
        table_ do
          tr_ do
            th_ "Zone"
            th_ "Pace range"
            th_ "Intensity"
          mapM_ trainingSection intervalPaces
        a_ [href_ "/"] "go back"

trainingSection :: PaceRange -> Html ()
trainingSection pace = tr_ do
  td_ (toHtml (name pace))
  td_ (toHtml paceText)
  td_ (toHtml (intensity pace))
  where
    minText = RT.formatRunTime (minPace pace)
    maxText = RT.formatRunTime (maxPace pace)
    paceText = minText <> " - " <> maxText <> " /km"
